- environment:
    host: String
    robot: String
    key: String
    value: String
    indices: host, key

- annotation, event, heartbeat:
    robot: String
    host: String
    label: String
    message: String
    tags: String[], Nullable
    level: String, Nullable
    end_time: DateTime, Nullable
    indices: robot+label

- metric, parameter:
    robot: String
    name: String
    real: Double, Nullable
    str: String, Nullable

- node_resource_utilization:
    robot: String
    node: String
    host: String
    process: String
    status: String
    cpu_percent: Double
    memory_percent: Double
    num_threads: Integer
    num_fds: Integer
    indices: robot

- joint_states_actual, joint_states_commanded:
    robot: String
    actuator: String
    position: Double
    velocity: Double
    effort: Double
    indices: robot, robot+actuator

- force_torque_sensor:
    robot: String
    actuator: String
    force: Double[]
    torque: Double[]
    indices: robot+actuator

- state_transitions:
    robot: String
    previous_state: String
    current_state: String
    state_enum: Integer
    state_string: String
    module: String, Nullable
    indices: robot+current_state

- topic_statistics:
    robot: String
    topic: String
    node_subscriber: String
    node_publisher: String
    start_time: DateTime
    end_time: DateTime
    dropped_messages: Integer
    delivered_messages: Integer
    traffic: Integer
    period_mean: Double
    period_stddev: Double
    period_max: Double
    stamp_age_mean: Double
    stamp_age_stddev: Double
    stamp_age_max: Double
    indices: robot+topic

- odom:
    robot: String
    frame: String
    position: Double[]
    orientation: Double[]
    rpy: Double[]
    indices: robot+frame

- estop:
    robot: String
    name: String
    type: Integer, Nullable
    state: Integer, Nullable
    state_string: String, Nullable

- signal_noise_ratio:
    robot: String
    iface: String
    snr: Double
