# -*- coding: utf-8 -*-

# Used to define supported (yaml config file) types and map them to SQLAlchemy types
cortex_type_map:
  - DateTime: DateTime(timezone=True)
  - Double: DOUBLE_PRECISION
  - Double[]: ARRAY(DOUBLE_PRECISION)
  - Integer: Integer
  - Integer[]: ARRAY(Integer)
  - String: String
  - String[]: ARRAY(String)
  - Boolean: Boolean
  - Boolean[]: ARRAY(Boolean)

# Used for special handling of certain row types
cortex_qualifiers:
  - Nullable
  - Unique
