@startuml

file spec [
Environment Table

---
{{yaml
    host: String
    robot: String
    key: String
    value: String
    indexes: host, key
}}
]

file table_generator [
CRTXTableGenerator
]

class "Environment Entity" {
- __tablename__ = ts_environment
+ time = Column(DateTime)
+ ros_time = Column(DateTime)
+ host = Column(String, index=True)
+ robot = Column(String)
+ key = Column(String, index=True)
+ value = Column(String)
}



spec -> table_generator
table_generator -> "Environment Entity"

@enduml