- robot:
    name: String, Unique
    description: String
    indexes: name
- actuator:
    name: String, Unique
    type: String
    make: String
    model: String
    serial: String, Nullable
    indexes: name
    foreign_keys: robot.id
- host:
    name: String, Unique
    ip_address: String
    indexes: name
