- environment:
    host: String
    robot: String
    key: String
    value: String
    indexes: host, key

- annotation, event, heartbeat:
    robot: String
    label: String
    message: String
    tags: String[], Nullable
    level: String, Nullable
    end_time: DateTime, Nullable
    indexes: robot+label

- metric, parameter:
    robot: String
    name: String
    real: Float64, Nullable
    str: String, Nullable

- node_resource_utilization:
    robot: String
    node: String
    host: String
    process: String
    status: String
    cpu_percent: Float64
    memory_percent: Float64
    num_threads: Int64
    num_fds: Int64
    indexes: robot+actuator

- joint_states_actual, joint_states_commanded:
    robot: String
    actuator: String
    position: Float64
    velocity: Float64
    effort: Float64
    indexes: robot, robot+actuator

- force_torque_sensor:
    robot: String
    actuator: String
    force: Float64[]
    torque: Float64[]
    indexes: robot+actuator

- state_transitions:
    robot: String
    previous_state: String
    current_state: String
    state_enum: Int64
    state_string: String
    module: String, Nullable
    indexes: robot+current_state

- topic_statistics:
    robot: String
    topic: String
    node_subscriber: String
    node_publisher: String
    start_time: DateTime
    end_time: DateTime
    dropped_messages: Int64
    delivered_messages: Int64
    traffic: Int64
    period_mean: Float64
    period_stddev: Float64
    period_max: Float64
    stamp_age_mean: Float64
    stamp_age_stddev: Float64
    stamp_age_max: Float64
    indexes: robot+topic

- odom:
    robot: String
    frame: String
    position: Float64[]
    orientation: Float64[]
    rpy: Float64[]
    indexes: robot+actuator
